# .github/workflows/main.yml

name: Test & Build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ludeeus/action-shellcheck@master
        continue-on-error: true
      - run: |
          exit 0

